/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Quick' at '7/29/16 5:00 PM' with Gradle 2.13
 *
 * @author Quick, @date 7/29/16 5:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
